sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: DAWq9wl6GSCWVzNuux+pJVCK87gi58AU9C934Mp1wBT8Yh2qm1XrVAFG2/pouDKQIQvoEVoD2PmQoyT64akF9e84xsy2xqNFkav2yhnQh8FOrsznXcdd5JU+SW73FiPF70rq2JYSZZKlsdPnUnk1FiAPhPpdbBoCZKnZASDLwLBU1ujVblxuLR0BUGtKYdQUKsLxZeXz+e+cbujUrR0+mW9FllH9fq44X4dVVzE8AT6mi4fhzSQMWFWWXtSmXxMueTpXCJ6oDxFpdpVsFyWWip3FUlG4k4+Ff0M3tUGAToXwAaIlF6EZtXxlLUC5zXU8tOr8DPRihCtXJS1l154H4LhR3eUNlSPTkGwSOpMu6NySEd2BHiVJuRskPVE+gbU2g3SeqtJdXPG7qZKhQ4gXbfbwhc3m+yt8JYIGEwZMzmVbt040KBu92kXL0zHLvcBQP346kDK+raPDMuYSuFV41sYrOMRC4kUIRe0GGoTznA1qkMqsKVZ2UXGrRiDVPWs/CFK/ZpSG+x/uSC3dDT+17ff3RamsZBF/ssYP1iBNB/szthvTwX10rhQ7QSMQqbob8WuPnEZIEz+ShULS/niaiuLcJ/kxqRl3WoSsVar/TFK7rKy+vsfuvpB4mXovWN+0Jq23hE/6O1HAPcXFH/y8QatWGDe2EXf05KVQnH74Rcg=
branches:
  only:
  - master
